# Generated by Django 2.2.3 on 2019-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20190910_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
