# Generated by Django 2.2.3 on 2019-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20190910_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
