# Generated by Django 2.2.3 on 2019-09-13 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_cuponproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuponproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuponProducto', to='productos.Producto'),
        ),
    ]
