# Generated by Django 2.1.8 on 2019-08-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190821_1319'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ManyToManyField(to='productos.Producto'),
        ),
    ]
