# Generated by Django 2.2.3 on 2019-09-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
