# Generated by Django 2.2.3 on 2019-09-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_venta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='metodoPago',
            field=models.CharField(max_length=20),
        ),
    ]
