# Generated by Django 2.2.3 on 2019-08-21 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='tienda/img')),
                ('telefono', models.PositiveIntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.BooleanField(default=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
            ],
        ),
    ]
