# Generated by Django 2.2.3 on 2019-09-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_auto_20190912_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='telefono',
            field=models.BigIntegerField(default=0),
        ),
    ]
