# Generated by Django 2.2.3 on 2019-09-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0003_auto_20190912_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
